// Generated by CoffeeScript 1.6.3
(function() {
  var exportObj;

  exportObj = typeof exports !== "undefined" && exports !== null ? exports : this;

  exportObj.demo = function(stage) {
    var falcon, layer, phantom;
    layer = new Kinetic.Layer();
    phantom = new Ship({
      stage: stage,
      name: 'Phantom',
      size: 'small',
      x: 100,
      y: 300,
      heading_deg: 112
    });
    falcon = new Ship({
      stage: stage,
      name: 'Falcon',
      size: 'large',
      x: 750,
      y: 600,
      heading_deg: 300
    });
    phantom.addTurn({
      before: new movements.Decloak({
        direction: 'leftforward',
        start_distance_from_front: 7,
        end_distance_from_front: 14
      }),
      during: new movements.Straight({
        speed: 3
      }),
      after: new movements.BarrelRoll({
        direction: 'right',
        start_distance_from_front: 20,
        end_distance_from_front: 0
      })
    });
    falcon.addTurn({
      during: new movements.Bank({
        direction: 'right',
        speed: 3
      }),
      after: new movements.Bank({
        direction: 'left',
        speed: 1
      })
    });
    falcon.addTurn({
      during: new movements.Bank({
        direction: 'left',
        speed: 3
      }),
      after: new movements.BarrelRoll({
        direction: 'right',
        speed: 1,
        start_distance_from_front: 0,
        end_distance_from_front: 60
      })
    });
    phantom.addTurn({
      during: new movements.Turn({
        speed: 2,
        direction: 'left'
      })
    });
    falcon.drawTurnFinalPosition(0, {
      stroke: 'black'
    });
    falcon.drawTurnFinalPosition(1, {
      stroke: 'green'
    });
    falcon.drawTurnMovement(2, {
      stroke: 'red'
    });
    phantom.drawTurnMovement(0, {
      stroke: 'black'
    });
    phantom.drawTurnMovement(1, {
      stroke: 'blue'
    });
    return phantom.drawTurnFinalPosition(2, {
      stroke: 'purple'
    });
  };

}).call(this);

/*
//@ sourceMappingURL=demo.map
*/
