// Generated by CoffeeScript 1.6.3
(function() {
  var exportObj;

  exportObj = typeof exports !== "undefined" && exports !== null ? exports : this;

  exportObj.drawDeployAreasOn = function(stage) {
    var deploylayer;
    deploylayer = new Kinetic.Layer({
      name: 'deployareas'
    });
    deploylayer.add(new Kinetic.Rect({
      name: 'northdeploy',
      x: 0,
      y: 0,
      width: stage.width(),
      height: exportObj.RANGE1,
      fillGreen: 255,
      fillAlpha: 0.1
    }));
    deploylayer.add(new Kinetic.Rect({
      name: 'southdeploy',
      x: 0,
      y: stage.height() - exportObj.RANGE1,
      width: stage.width(),
      height: exportObj.RANGE1,
      fillGreen: 255,
      fillAlpha: 0.1
    }));
    return stage.add(deploylayer);
  };

}).call(this);

/*
//@ sourceMappingURL=deployarea.map
*/
