// Generated by CoffeeScript 1.6.3
(function() {
  var exportObj;

  exportObj = typeof exports !== "undefined" && exports !== null ? exports : this;

  exportObj.FiringArc = (function() {
    function FiringArc(args) {
      var _ref, _ref1;
      this.base = args.base;
      this.rotation = parseFloat((_ref = args.rotation) != null ? _ref : 0);
      this.angle = parseFloat((_ref1 = args.angle) != null ? _ref1 : exportObj.PRIMARY_FIRING_ARC_DEG);
      this.group = new Kinetic.Group({
        name: 'firing_arc_group',
        x: this.base.position.x,
        y: this.base.position.y,
        rotation: (this.base.position.heading_deg + this.rotation + 270) % 360
      });
      this.addArcAtRange(exportObj.RANGE1, 0.3);
      this.addArcAtRange(exportObj.RANGE2, 0.2);
      this.addArcAtRange(exportObj.RANGE3, 0.1);
    }

    FiringArc.prototype.addArcAtRange = function(range, alpha) {
      this.group.add(new Kinetic.Arc({
        name: 'firing_arc_range_left_arc',
        x: this.base.width / 2,
        y: -this.base.width / 2,
        angle: this.angle / 2,
        innerRadius: 0,
        outerRadius: range,
        fillRed: 255,
        fillAlpha: alpha,
        rotationDeg: -this.angle / 2
      }));
      this.group.add(new Kinetic.Arc({
        name: 'firing_arc_range_right_arc',
        x: this.base.width / 2,
        y: this.base.width / 2,
        angle: this.angle / 2,
        innerRadius: 0,
        outerRadius: range,
        fillRed: 255,
        fillAlpha: alpha
      }));
      return this.group.add(new Kinetic.Rect({
        name: 'firinc_arc_range_center',
        x: this.base.width / 2,
        y: -this.base.width / 2,
        width: range,
        height: this.base.width,
        fillRed: 255,
        fillAlpha: alpha
      }));
    };

    FiringArc.prototype.destroy = function() {};

    FiringArc.prototype.draw = function(layer) {
      var child, _i, _len, _ref, _results;
      if (layer == null) {
        layer = this.base.group.getLayer();
      }
      layer.add(this.group);
      _ref = this.group.children;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        child = _ref[_i];
        _results.push(child.draw());
      }
      return _results;
    };

    return FiringArc;

  })();

}).call(this);

/*
//@ sourceMappingURL=firingarc.map
*/
