// Generated by CoffeeScript 1.6.3
(function() {
  var exportObj;

  exportObj = typeof exports !== "undefined" && exports !== null ? exports : this;

  exportObj.drawGridOn = function(stage) {
    var gridlayer, strokeWidth, x, y, _i, _j, _ref, _ref1;
    gridlayer = new Kinetic.Layer();
    for (x = _i = 0, _ref = stage.width(); _i <= _ref; x = _i += 25) {
      strokeWidth = x % 100 === 0 ? 3 : 1;
      gridlayer.add(new Kinetic.Line({
        points: [x, 0, x, stage.height()],
        stroke: 'cyan',
        strokeWidth: strokeWidth
      }));
    }
    for (y = _j = 0, _ref1 = stage.height(); _j <= _ref1; y = _j += 25) {
      strokeWidth = y % 100 === 0 ? 3 : 1;
      gridlayer.add(new Kinetic.Line({
        points: [0, y, stage.width(), y],
        stroke: 'cyan',
        strokeWidth: strokeWidth
      }));
    }
    return stage.add(gridlayer);
  };

}).call(this);

/*
//@ sourceMappingURL=grid.map
*/
