// Generated by CoffeeScript 1.6.3
(function() {
  var Movement, exportObj,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  exportObj = typeof exports !== "undefined" && exports !== null ? exports : this;

  exportObj.movements = {};

  Movement = (function() {
    function Movement(args) {
      this.speed = args.speed;
      this.direction = args.direction;
    }

    Movement.prototype.getBaseTransformAndHeading = function(base) {
      throw new Error('Base class; implement me!');
    };

    return Movement;

  })();

  exportObj.movements.Straight = (function(_super) {
    __extends(Straight, _super);

    function Straight(args) {
      Straight.__super__.constructor.call(this, args);
    }

    Straight.prototype.getBaseTransformAndHeading = function(base) {
      return {
        transform: base.getFrontNubTransform().translate(0, -this.speed * exportObj.SMALL_BASE_WIDTH - (base.width / 2)),
        heading_deg: base.position.heading_deg
      };
    };

    return Straight;

  })(Movement);

  exportObj.movements.Koiogran = (function(_super) {
    __extends(Koiogran, _super);

    function Koiogran(args) {
      Koiogran.__super__.constructor.call(this, args);
    }

    Koiogran.prototype.getBaseTransformAndHeading = function(base) {
      return {
        transform: base.getFrontNubTransform().translate(0, -this.speed * exportObj.SMALL_BASE_WIDTH - (base.width / 2)),
        heading_deg: (base.position.heading_deg + 180) % 360
      };
    };

    return Koiogran;

  })(Movement);

  exportObj.movements.Bank = (function(_super) {
    __extends(Bank, _super);

    function Bank(args) {
      Bank.__super__.constructor.call(this, args);
    }

    Bank.prototype.getBaseTransformAndHeading = function(base) {
      var d, rotation, transform;
      switch (this.direction) {
        case 'left':
          d = exportObj.BANK_INSIDE_RADII[this.speed] + (exportObj.TEMPLATE_WIDTH / 2);
          rotation = 315;
          transform = base.getFrontNubTransform().translate(-d, 0).rotate(-Math.PI / 4).translate(d, -base.width / 2);
          break;
        case 'right':
          d = exportObj.BANK_INSIDE_RADII[this.speed] + (exportObj.TEMPLATE_WIDTH / 2);
          rotation = 45;
          transform = base.getFrontNubTransform().translate(d, 0).rotate(Math.PI / 4).translate(-d, -base.width / 2);
          break;
        default:
          throw new Error("Invalid direction " + this.direction);
      }
      return {
        transform: transform,
        heading_deg: (base.position.heading_deg + rotation) % 360
      };
    };

    return Bank;

  })(Movement);

  exportObj.movements.Turn = (function(_super) {
    __extends(Turn, _super);

    function Turn(args) {
      Turn.__super__.constructor.call(this, args);
    }

    Turn.prototype.getBaseTransformAndHeading = function(base) {
      var d, rotation, transform;
      switch (this.direction) {
        case 'left':
          d = exportObj.TURN_INSIDE_RADII[this.speed] + (exportObj.TEMPLATE_WIDTH / 2);
          rotation = 270;
          transform = base.getFrontNubTransform().translate(-d, 0).rotate(-Math.PI / 2).translate(d, -base.width / 2);
          break;
        case 'right':
          d = exportObj.TURN_INSIDE_RADII[this.speed] + (exportObj.TEMPLATE_WIDTH / 2);
          rotation = 90;
          transform = base.getFrontNubTransform().translate(d, 0).rotate(Math.PI / 2).translate(-d, -base.width / 2);
          break;
        default:
          throw new Error("Invalid direction " + this.direction);
      }
      return {
        transform: transform,
        heading_deg: (base.position.heading_deg + rotation) % 360
      };
    };

    return Turn;

  })(Movement);

  exportObj.movements.BarrelRoll = (function(_super) {
    __extends(BarrelRoll, _super);

    function BarrelRoll(args) {
      BarrelRoll.__super__.constructor.call(this, args);
      if (args.start_distance_from_front == null) {
        throw new Error('Missing argument start_distance_from_front');
      }
      this.start_distance_from_front = args.start_distance_from_front;
      if (args.end_distance_from_front == null) {
        throw new Error('Missing argument end_distance_from_front');
      }
      this.end_distance_from_front = args.end_distance_from_front;
    }

    BarrelRoll.prototype.getBaseTransformAndHeading = function(base) {
      var d, rotation, transform, x_offset, y_offset;
      x_offset = (this.speed * exportObj.SMALL_BASE_WIDTH) + (base.width / 2);
      y_offset = ((base.width - exportObj.TEMPLATE_WIDTH) / 2) - this.end_distance_from_front;
      switch (this.direction) {
        case 'left':
          rotation = 0;
          transform = base.getBarrelRollTransform(this.direction, this.start_distance_from_front).translate(-x_offset, y_offset);
          break;
        case 'right':
          rotation = 0;
          transform = base.getBarrelRollTransform(this.direction, this.start_distance_from_front).translate(x_offset, y_offset);
          break;
        case 'leftforward':
          d = exportObj.BANK_INSIDE_RADII[this.speed] + (exportObj.TEMPLATE_WIDTH / 2);
          rotation = 45;
          transform = base.getBarrelRollTransform(this.direction, this.start_distance_from_front).translate(0, -d).rotate(Math.PI / 4).translate(-base.width / 2, d + y_offset);
          break;
        case 'leftbackward':
          d = exportObj.BANK_INSIDE_RADII[this.speed] + (exportObj.TEMPLATE_WIDTH / 2);
          rotation = 315;
          transform = base.getBarrelRollTransform(this.direction, this.start_distance_from_front).translate(0, d).rotate(-Math.PI / 4).translate(-base.width / 2, -d + y_offset);
          break;
        case 'rightforward':
          d = exportObj.BANK_INSIDE_RADII[this.speed] + (exportObj.TEMPLATE_WIDTH / 2);
          rotation = 315;
          transform = base.getBarrelRollTransform(this.direction, this.start_distance_from_front).translate(0, -d).rotate(-Math.PI / 4).translate(base.width / 2, d + y_offset);
          break;
        case 'rightbackward':
          d = exportObj.BANK_INSIDE_RADII[this.speed] + (exportObj.TEMPLATE_WIDTH / 2);
          rotation = 45;
          transform = base.getBarrelRollTransform(this.direction, this.start_distance_from_front).translate(0, d).rotate(Math.PI / 4).translate(base.width / 2, -d + y_offset);
      }
      return {
        transform: transform,
        heading_deg: (base.position.heading_deg + rotation) % 360
      };
    };

    return BarrelRoll;

  })(Movement);

}).call(this);

/*
//@ sourceMappingURL=movement.map
*/
