// Generated by CoffeeScript 1.6.3
(function() {
  var exportObj;

  exportObj = typeof exports !== "undefined" && exports !== null ? exports : this;

  exportObj.Position = (function() {
    function Position(args) {
      this.center_x = args.center_x;
      this.center_y = args.center_y;
      this.heading_deg = args.heading_deg;
    }

    return Position;

  })();

}).call(this);

/*
//@ sourceMappingURL=position.map
*/
